name: govee_lights_control
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/tytydraco/govee_lights_control

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.6.0
  meta: ^1.17.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.0.0
